#!/usr/bin/env python

SPI_DOUT = 1
SPI_DIN = 2
SPI_CLK = 4
SPI_CS_B = 8
SUBSECTOR_SIZE = 4096
SECTOR_SIZE = 65536

# SRP0_NV = 1 [7], TBPROT=1 [6], BP=XXXX [5:2]
LOCK_REGION_BOOTLOADER = 0xD8
LOCK_REGION_BOOTLOADER_RUNTIME = 0xDC
LOCK_REGION_SPARTAN_KINTEX = 0xE4
LOCK_REGION_ALL = 0xFC
